services:
  - type: web
    name: suhbatai
    runtime: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENROUTER_API_KEY
        value: sk-or-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    plan: free
